// src/ai/flows/generate-empathetic-response.ts
'use server';

/**
 * @fileOverview AI chat companion that generates empathetic responses, acting as a specialist therapy psychologist.
 *
 * - generateEmpatheticResponse - A function that generates empathetic responses.
 * - GenerateEmpatheticResponseInput - The input type for the generateEmpatheticResponse function.
 * - GenerateEmpatheticResponseOutput - The return type for the generateEmpatheticResponse function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateEmpatheticResponseInputSchema = z.object({
  userInput: z.string().describe('The user input to respond to.'),
});
export type GenerateEmpatheticResponseInput = z.infer<typeof GenerateEmpatheticResponseInputSchema>;

const GenerateEmpatheticResponseOutputSchema = z.object({
  response: z.string().describe('The empathetic response generated by the AI.'),
});
export type GenerateEmpatheticResponseOutput = z.infer<typeof GenerateEmpatheticResponseOutputSchema>;

export async function generateEmpatheticResponse(
  input: GenerateEmpatheticResponseInput
): Promise<GenerateEmpatheticResponseOutput> {
  return generateEmpatheticResponseFlow(input);
}

const empatheticResponsePrompt = ai.definePrompt({
  name: 'empatheticResponsePrompt',
  input: {schema: GenerateEmpatheticResponseInputSchema},
  output: {schema: GenerateEmpatheticResponseOutputSchema},
  prompt: `You are an AI specialist therapy psychologist.

  Your primary goal is to provide empathetic support, validate the user's feelings, and encourage them to share more if they wish.
  You should focus on active listening and creating a safe space for conversation.
  It is crucial that you AVOID giving direct advice, making diagnoses, or offering solutions. Your role is to listen and reflect.

  Here are some example phrases to guide your tone and approach:
  - "I'm here to listen and support you."
  - "It sounds like you're going through a lot."
  - "I'm here to understand more about what you're experiencing, if you're comfortable sharing."
  - "It's understandable that you feel that way given the circumstances."
  - "I hear you, and I want to acknowledge the difficulty of what you're describing."

  User Input: {{{userInput}}}

  Empathetic Response:`,
});

const generateEmpatheticResponseFlow = ai.defineFlow(
  {
    name: 'generateEmpatheticResponseFlow',
    inputSchema: GenerateEmpatheticResponseInputSchema,
    outputSchema: GenerateEmpatheticResponseOutputSchema,
  },
  async input => {
    const {output} = await empatheticResponsePrompt(input);
    return output!;
  }
);

