// src/ai/flows/generate-empathetic-response.ts
'use server';

/**
 * @fileOverview AI chat companion that generates empathetic responses, acting as a specialist therapy psychologist.
 *
 * - generateEmpatheticResponse - A function that generates empathetic responses.
 * - GenerateEmpatheticResponseInput - The input type for the generateEmpatheticResponse function.
 * - GenerateEmpatheticResponseOutput - The return type for the generateEmpatheticResponse function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateEmpatheticResponseInputSchema = z.object({
  userInput: z.string().describe('The user input to respond to.'),
});
export type GenerateEmpatheticResponseInput = z.infer<typeof GenerateEmpatheticResponseInputSchema>;

const GenerateEmpatheticResponseOutputSchema = z.object({
  response: z.string().describe('The empathetic response generated by the AI.'),
});
export type GenerateEmpatheticResponseOutput = z.infer<typeof GenerateEmpatheticResponseOutputSchema>;

export async function generateEmpatheticResponse(
  input: GenerateEmpatheticResponseInput
): Promise<GenerateEmpatheticResponseOutput> {
  return generateEmpatheticResponseFlow(input);
}

const empatheticResponsePrompt = ai.definePrompt({
  name: 'empatheticResponsePrompt',
  input: {schema: GenerateEmpatheticResponseInputSchema},
  output: {schema: GenerateEmpatheticResponseOutputSchema},
  prompt: `You’re a chill but emotionally intelligent AI who acts like a therapist-bestie. You’re here to really listen, validate feelings, and gently guide users through tough emotions. You use a warm, supportive tone — casual but not silly.

You know therapy concepts like CBT, grounding, journaling, and self-awareness. You never judge, never rush advice. You ask questions, offer reflection, and help people understand their emotions better.

Don’t act like a doctor. Avoid diagnosis. If someone’s in real crisis, tell them kindly to reach out to a real person or helpline.

Be supportive. Be safe. Be real. Keep replies short, honest, and comforting — like a friend who really gets it.

User Input: {{{userInput}}}

Empathetic Response:`,
});

const generateEmpatheticResponseFlow = ai.defineFlow(
  {
    name: 'generateEmpatheticResponseFlow',
    inputSchema: GenerateEmpatheticResponseInputSchema,
    outputSchema: GenerateEmpatheticResponseOutputSchema,
  },
  async input => {
    const {output} = await empatheticResponsePrompt(input);
    return output!;
  }
);
